#!/usr/bin/env node
// GENERATOR for src/renderer/src/settings/emojiData.generated.ts — every emoji
// the space-emoji picker (Settings → Spaces → Representational emoji) offers,
// with its English name and search words.
//
// Source: emojibase-data (MIT), which packages Unicode's emoji list with the
// CLDR English names and keywords. It is NOT a dependency: fetch it, point
// this at it, commit the output.
//
//   cd <somewhere temporary> && npm pack emojibase-data@17.0.0 && tar -xzf emojibase-data-17.0.0.tgz
//   node tools/emoji/generate-emoji.mjs <that folder>/package
//
// What is left out, and why:
// - Unicode's "component" group (skin-tone swatches, hair pieces, bare
//   regional letters) — parts of other emoji, not emoji to pick.
// - Skin-tone variants — the one-colour set has no skin tones to show.
// - Anything newer than MAX_VERSION: Windows' own colour emoji font lags the
//   Mac's, and a space emoji that draws as an empty box on Windows is worse
//   than one fewer choice. Raise it once Windows has caught up.
// - SKIP: emoji one of the two sets cannot draw (measured 2026-09-28 by
//   drawing every one in Chromium with Noto Emoji and Apple Color Emoji).
//
// Each emoji is emojibase's `emoji` field, NOT one rebuilt from `hexcode`:
// hexcode drops the U+FE0F that a text-by-default emoji needs to draw in
// colour (☺ and ✏ came out as plain black symbols in the colour look,
// 2026-09-28). The extra U+FE0F `emoji` puts on an emoji that is colour
// anyway (📚️) is harmless. The one-colour set strips U+FE0F before drawing
// — see `shownEmoji` in shared/settings.ts.
//
// Never hand-edit the generated file — same rule as tools/licenses' output.

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(fileURLToPath(new URL('.', import.meta.url)), '../..')
const OUT = path.join(ROOT, 'src/renderer/src/settings/emojiData.generated.ts')

const src = process.argv[2]
if (!src) {
  console.error('usage: node tools/emoji/generate-emoji.mjs <emojibase-data package folder>')
  process.exit(1)
}
const pkg = JSON.parse(readFileSync(path.join(src, 'package.json'), 'utf8'))
const data = JSON.parse(readFileSync(path.join(src, 'en/data.json'), 'utf8'))

const MAX_VERSION = 15.1
const COMPONENT_GROUP = 2
/** a space emoji is capped at 16 UTF-16 units (shared/settings.ts EMOJI_MAX) */
const MAX_UNITS = 16
const SKIP = new Set([
  '26D3-FE0F-200D-1F4A5' // broken chain — neither set draws it as one emoji
])

// Unicode's group order, with the short names the picker shows.
const GROUPS = new Map([
  [0, 'Smileys'],
  [1, 'People'],
  [3, 'Nature'],
  [4, 'Food'],
  [5, 'Places'],
  [6, 'Activities'],
  [7, 'Objects'],
  [8, 'Symbols'],
  [9, 'Flags']
])

// Search words CLDR does not give but people type. Keyed by hexcode. The first
// block is the old curated picker's own words (before 2026-09-28 it offered 80
// hand-picked emoji), kept so nothing that used to be findable stops being.
const EXTRA = {
  '1F4DD': 'notes write pencil',
  '1F4CE': 'attach',
  '1F4CC': 'mark',
  '1F4D3': 'journal',
  '1F4DA': 'library study',
  '1F516': 'tag label',
  '1F511': 'unlock',
  '1F4BC': 'work business',
  '1F4E6': 'archive',
  '1F9F0': 'kit',
  '1F9EA': 'lab experiment',
  '1F4BB': 'code',
  '1F4F1': 'mobile device',
  '2B50': 'favourite favorite',
  '2728': 'new',
  '1F525': 'trending',
  '26A1': 'fast',
  '1F3AF': 'goal focus',
  '1F9E9': 'project',
  '2705': 'done complete tick',
  '274C': 'no cancel wrong',
  '1F48E': 'premium',
  '1F3A8': 'creative',
  '1F3AE': 'gaming',
  '1F333': 'forest',
  // Unicode has no skirt; the dress is the nearest thing to it.
  '1F457': 'skirt'
}

// tabs and newlines are the row/field separators below
const clean = (s) => s.replace(/[\t\n]+/g, ' ').trim()

const byGroup = new Map([...GROUPS.keys()].map((g) => [g, []]))
let count = 0
for (const e of [...data].sort((a, b) => (a.order ?? 0) - (b.order ?? 0))) {
  if (!byGroup.has(e.group) || e.group === COMPONENT_GROUP) continue
  if ((e.version ?? 0) > MAX_VERSION || SKIP.has(e.hexcode)) continue
  const emoji = e.emoji
  if (emoji.length > MAX_UNITS) continue
  const words = clean([...(e.tags ?? []), EXTRA[e.hexcode] ?? ''].join(' '))
  byGroup.get(e.group).push(`${emoji}\t${clean(e.label)}\t${words}`)
  count++
}

const body = [...GROUPS]
  .map(([g, name]) => `  { group: ${JSON.stringify(name)}, rows: ${JSON.stringify(byGroup.get(g).join('\n'))} }`)
  .join(',\n')

writeFileSync(
  OUT,
  `// GENERATED by tools/emoji/generate-emoji.mjs from ${pkg.name} ${pkg.version} — do not hand-edit.
// Emoji, names and keywords: Unicode + CLDR (Unicode License), packaged by emojibase (MIT).
// ${count} emoji. Each row is "emoji<TAB>name<TAB>search words", one per line.

export const EMOJI_DATA: { group: string; rows: string }[] = [
${body}
]
`
)
console.log(`wrote ${count} emoji to ${path.relative(ROOT, OUT)}`)
