"""
Rebuild the alise draw as ONE continuous pen.

  * ONE dot for the whole word instead of five. It never fades in or out - it cuts on
    when the first stroke starts and off when the last one ends - and it travels the
    gaps between strokes rather than teleporting, so alise reads as one hand writing
    one word.
  * Dot radius is CONSTANT at the font's own stroke weight (no longer ballooning to
    match local thickness on the fat parts of a letter).
  * Everything is linear, with all pacing carried by the keyframe positions, so the ink
    front and the dot cannot drift apart.

STROKE ORDER IS NOT DECIDED HERE ANY MORE (2026-08-12). geometry.json's `center_d` is
now the finished pen route for each letter - complete, and already in the order a hand
writes it - emitted by `build_centerlines.py`. So `strokes_for()` is the identity, and
the index-slicing stroke plans that used to live in it are gone. They were only ever
needed because the old centerlines missed whole limbs of some letters and had to be
re-cut by hand; read build_centerlines.py's docstring for what that cost.

Mask widths come from the true coverage requirement (every outline point must be
reachable from its nearest centerline sample). That requirement has not changed - what
changed is that a centerline which actually visits the whole letter satisfies it at
roughly the stroke's own width, instead of at up to 1657 units against a 340-unit pen.
Watch the width printout at the end of a run: values near 340-500 are healthy, and
anything approaching four figures means a letter has a limb the pen never reaches, which
will show up as ink flashing on nowhere near the dot.
"""
import argparse, json, os, re, sys
import numpy as np


def _no_match(what):
    sys.exit(
        f"gen_pen: nothing matched for {what} — is this the right --out file, and "
        "does it still carry that markup?"
    )


def must_sub(pattern, repl, text, what, count=0, flags=0):
    """`re.sub` is a SILENT no-op when nothing matches, and this script's entire job
    is rewriting an HTML file it does not own. Point --out at a page missing one of
    the recognised markers and the run used to print its normal success line while
    writing a file with no animation wired into it at all.

    Counts matches rather than comparing before/after: a re-run that writes exactly
    what is already there matches fine and must NOT be reported as a failure."""
    out, n = re.subn(pattern, repl, text, count=count, flags=flags)
    if n == 0:
        _no_match(what)
    return out


def must_replace(text, target, repl, what):
    """The `str.replace` counterpart of must_sub, same reasoning."""
    if target not in text:
        _no_match(what)
    return text.replace(target, repl)

HERE = os.path.dirname(os.path.abspath(__file__))
SCRATCH = HERE            # outlines.json lives beside this script

LETTERS = ["a", "l", "i", "s", "e"]
ALISE_START = 1000      # ms; was 1300 - closes the dead gap after "Note" finishes at 850
# Chosen 2026-08-12 from three rendered variants (3.50 / 3.00 / 2.50s) against the 4.15s
# it had been: alise finishes at ALISE_START + TOTAL_DRAW + 4*CONNECT_MS = 2998ms, 28%
# quicker. CONNECT_MS was scaled with TOTAL_DRAW rather than left at 50, so pen travel
# stays the same FRACTION of the draw - left alone it would have grown to 13% of a shorter
# animation and read as four pauses.
# "Note" is deliberately NOT part of this: its typing (250-850ms) and the pause after it
# are hand-written CSS that the generator never touches, and 0-1000ms was verified
# pixel-identical to the slower build before this landed. Reuben's condition, checked.
TOTAL_DRAW = 1870       # ms of actual inking across the whole word (was 2950, orig 3600)
CONNECT_MS = 32         # ms per pen travel between strokes (was 50)

# Speed variants are generated by pointing --out at a copy, so site/index.html is only
# touched when that is what you actually mean. --total-draw and --connect are the two
# knobs that change how fast alise is written; everything before it ("Note" typing, and
# the pause after it) is governed by ALISE_START and is deliberately not scaled with them.
_ap = argparse.ArgumentParser(description=__doc__)
_ap.add_argument("--out", default=os.path.join(HERE, "..", "..", "site", "index.html"),
                 help="HTML file to rewrite in place (default: site/index.html)")
_ap.add_argument("--total-draw", type=float, default=None, help="ms of inking across the word")
_ap.add_argument("--connect", type=float, default=None, help="ms per pen travel between letters")
_args = _ap.parse_args()
HTML = _args.out
if _args.total_draw is not None:
    TOTAL_DRAW = _args.total_draw
if _args.connect is not None:
    CONNECT_MS = _args.connect
DOT_R = 170             # constant, = the font's own stroke weight

# SWEEP_W / SWEEP_RUNUP / SWEEP_TAIL_MS lived here for one afternoon (2026-08-13) and
# belonged to a swept-mask reveal front that was tried and removed the same day - the
# emit block records why. The reveal is the gated slices; there is no sweep to tune.
STROKE_HALF = 95.0
MASK_SAFETY = 1.10
# KF_PER_LETTER, END_EXTEND, HEAD_REVEAL_MS and BAND_STROKE_OVERLAP lived here until
# 2026-08-12. All four belonged to the swept-stroke reveal - keyframe density for its
# dashoffset curve, the overhang a butt cap needed to cover a terminal tip, the time that
# overhang was taken up in, and the overlap that stopped two antialiased butt edges landing
# on the same line. The reveal is slices now (see build_centerlines.py) and strokes nothing,
# so they are gone rather than left lying around to be tuned by someone with no effect.
STEP = 7.0
GRID = 6.0              # user units per cell when measuring how much new ink a sample lays
SMOOTH_W = 15           # samples; smooths the new-ink rate so the pen eases, not jerks
MIN_SPEED = 0.30        # dt/ds floor: how briskly the pen crosses ink it already laid
MAX_SPEED = 2.00        # dt/ds ceiling: how long it may linger where a lot is appearing
KF_PER_STROKE = 24      # pen keyframes per stroke, so the dot tracks a varying speed
ALISE_SCALE = 0.93
# Raise alise so it reads as being on Note's line.
#   INK_DROP is MEASURED off the real render by measure_align.py, never derived: em of
#   alise ink below the text baseline, per unit of ALISE_SCALE, with no nudge applied.
#   The 190 stroke is most of it - it hangs the painted glyph well below the baseline the
#   outline was traced against. The derivation that used to sit here was out by about half
#   a pixel, and was being written into a property that does nothing anyway (see the CSS
#   emitted at the bottom of this file).
#
#   OVERSHOOT is how far alise's lowest ink is allowed to fall below Note's flat N/t feet.
#   Note's own round letters overshoot 0.0098em, and matching that was the first thing
#   tried - typographically it is the "correct" answer, since every alise letter is
#   round-bottomed. Reuben compared four renders on 2026-08-12 and chose FLUSH (0): this
#   script is heavy enough, and set low enough against a 700-weight sans, that giving it
#   the o/e overshoot as well still read as sagging. Taste beat the rule; don't "fix" it
#   back to 0.0098 on principle.
INK_DROP = 0.038244
OVERSHOOT = 0.0
NUDGE = INK_DROP * ALISE_SCALE - OVERSHOOT


def parse_subpaths(d):
    subs, cur = [], []
    for c, x, y in re.findall(r"([ML])\s*(-?[\d.]+)\s+(-?[\d.]+)", d):
        if c == "M":
            if len(cur) > 1: subs.append(np.array(cur, float))
            cur = [(float(x), float(y))]
        else:
            cur.append((float(x), float(y)))
    if len(cur) > 1: subs.append(np.array(cur, float))
    return subs


def densify(pts, step=STEP):
    out = []
    for i in range(len(pts) - 1):
        seg = pts[i + 1] - pts[i]
        L = float(np.hypot(*seg))
        n = max(1, int(L / step))
        for k in range(n):
            out.append(pts[i] + seg * (k / n))
    out.append(pts[-1])
    return np.array(out)


def plen(p):
    return float(np.sum(np.linalg.norm(np.diff(p, axis=0), axis=1)))


def strokes_for(letter, subs):
    """Identity. geometry.json's center_d already IS the route, in writing order -
    build_centerlines.py decides it. Kept as a seam so a one-off per-letter override
    has an obvious home, but nothing should need one."""
    return list(subs)


html = open(HTML, encoding="utf-8").read()
raw_outlines = json.load(open(os.path.join(SCRATCH, "outlines.json")))
outlines = [np.array(g["outline"], float)[::2] for g in raw_outlines]
geom = json.load(open(os.path.join(SCRATCH, "geometry.json")))["letters"]
assert [g["name"] for g in geom] == LETTERS, "geometry.json letter order"
# outlines.json is indexed POSITIONALLY against geom below (outlines[gi] is paired
# with geom[gi]'s coverage), and until 2026-08-20 only geometry.json's order was
# ever checked. If a future sample ever renders the SVG groups in a different
# order, the wrong outline pairs with the wrong letter — no crash, just a quietly
# corrupted reveal shipped into site/index.html. sample_outlines.py records each
# group's own letter now, so that can be checked rather than assumed; an older
# file with no names still works, count-checked only.
assert len(outlines) == len(LETTERS), \
    f"outlines.json has {len(outlines)} letters, expected {len(LETTERS)} — re-run sample_outlines.py"
_names = [g.get("name") for g in raw_outlines]
if any(n is not None for n in _names):
    assert _names == LETTERS, f"outlines.json letter order is {_names}, expected {LETTERS}"
else:
    print("note: outlines.json predates letter names — order assumed, not verified")

letter_paths, all_strokes = [], []      # all_strokes: (letter_index, densified points)
for gi, g in enumerate(geom):
    letter_paths.append(g["letter_d"])
    for st in strokes_for(LETTERS[gi], parse_subpaths(g["center_d"])):
        if len(st) > 1:
            all_strokes.append((gi, densify(np.array(st, float))))

# ---- coverage: how wide the reveal has to be at each sample --------------------------
# Solved per LETTER across all of its strokes at once. Doing it per stroke makes every
# stroke responsible for the whole letter (the "i" body would have to reach its own
# tittle), which blows the widths up by an order of magnitude.
cov_by_stroke = {}
for gi in range(5):
    idxs = [n for n, (g2, _) in enumerate(all_strokes) if g2 == gi]
    # np.vstack on an empty list raises a bare "need at least one array to
    # concatenate", which says nothing about WHICH letter is malformed. This
    # happens when geometry.json's center_d for a letter is empty, or when every
    # one of its subpaths was filtered out above as too short (len <= 1).
    assert idxs, (
        f"no centreline strokes for {LETTERS[gi]!r} — geometry.json's center_d for it is "
        "empty or every subpath is a single point; re-run build_centerlines.py"
    )
    C = np.vstack([all_strokes[n][1] for n in idxs])
    O = outlines[gi]
    d2 = ((O[:, None, :] - C[None, :, :]) ** 2).sum(-1)
    nearest, dist = d2.argmin(1), np.sqrt(d2.min(1))
    cov = np.zeros(len(C))
    np.maximum.at(cov, nearest, dist)
    cov = np.maximum(cov, np.sqrt(d2.min(0)))
    k = 9
    pad = np.pad(cov, k // 2, mode="edge")
    cov = np.array([pad[j:j + k].max() for j in range(len(cov))]) + STROKE_HALF
    off = 0
    for n in idxs:
        m = len(all_strokes[n][1])
        cov_by_stroke[n] = cov[off:off + m]
        off += m


def new_ink(pts, radius):
    """How much NEW ink each sample exposes — measured, by sweeping the reveal disc over
    a grid and counting cells that were not already covered.

    Time is handed out in proportion to this, and that is the whole point: the ink front
    should advance evenly, and under constant pen speed it does not. Two separate things
    break it, and counting pixels catches both without modelling either.

      * The disc's radius follows the letter's local thickness, so it is not constant.
        Where it grows, the front runs out ahead of the pen; where it shrinks, the front
        stops dead while the pen carries on. That is the hitch in `s` about a third of the
        way through, where consecutive segment widths run 401, 401, 362, 268.
      * Where the stroke crosses or doubles back on itself the disc is over ink that is
        already painted and contributes nothing at all. `a` does this deliberately (it
        comes back down its own stem); `s` and `e` each cross once.

    Under constant speed both read the same way to a viewer: the ink stops while the dot
    keeps going. And because the dot is the same colour as the ink it is crossing, that
    looks like the animation hanging rather than like a pen travelling."""
    x0, y0 = pts.min(0) - radius.max() - GRID
    x1, y1 = pts.max(0) + radius.max() + GRID
    W = int((x1 - x0) / GRID) + 2
    H = int((y1 - y0) / GRID) + 2
    gx = x0 + np.arange(W) * GRID
    gy = y0 + np.arange(H) * GRID
    covered = np.zeros((H, W), bool)
    gained = np.zeros(len(pts))
    for i, (p, r) in enumerate(zip(pts, radius)):
        cx0 = max(0, int((p[0] - r - x0) / GRID))
        cx1 = min(W, int((p[0] + r - x0) / GRID) + 2)
        cy0 = max(0, int((p[1] - r - y0) / GRID))
        cy1 = min(H, int((p[1] + r - y0) / GRID) + 2)
        sub = covered[cy0:cy1, cx0:cx1]
        dx = gx[cx0:cx1] - p[0]
        dy = gy[cy0:cy1] - p[1]
        disc = (dx[None, :] ** 2 + dy[:, None] ** 2) <= r * r
        gained[i] = np.count_nonzero(disc & ~sub)
        sub |= disc
    return gained


def weighted_cum(pts, w):
    """Cumulative 'time length' along a stroke, and its total."""
    seg = np.linalg.norm(np.diff(pts, axis=0), axis=1)
    wseg = seg * 0.5 * (w[:-1] + w[1:])
    return np.concatenate([[0.0], np.cumsum(wseg)])


def ink_weights(pts, cov):
    """dt/ds, from new ink per unit length: linger where a lot of ink is appearing, hurry
    where little or none is. Normalised to a median of 1 and clamped, so a stretch the pen
    has already painted is crossed briskly rather than teleported over."""
    seg = np.linalg.norm(np.diff(pts, axis=0), axis=1)
    seg = np.concatenate([[seg[0]], seg])
    rate = new_ink(pts, cov * MASK_SAFETY) / np.maximum(seg, 1e-9)
    pad = np.pad(rate, SMOOTH_W // 2, mode="edge")
    rate = np.convolve(pad, np.ones(SMOOTH_W) / SMOOTH_W, "valid")[:len(rate)]
    ref = np.median(rate[rate > 0]) if np.any(rate > 0) else 1.0
    return np.clip(rate / max(ref, 1e-9), MIN_SPEED, MAX_SPEED)


# ---- schedule: the pen spends its time where ink appears -----------------------------
weights = [ink_weights(p, cov_by_stroke[i]) for i, (_, p) in enumerate(all_strokes)]
wcums = [weighted_cum(p, w) for (_, p), w in zip(all_strokes, weights)]
total_w = sum(c[-1] for c in wcums)
t = ALISE_START
pieces = []          # (kind, letter, points, t0, t1, tfrac per sample, weights, stroke)
for i, ((gi, pts), wc, w) in enumerate(zip(all_strokes, wcums, weights)):
    dur = TOTAL_DRAW * wc[-1] / total_w
    pieces.append(("ink", gi, pts, t, t + dur, wc / wc[-1], w, i))
    t += dur
    if i < len(all_strokes) - 1:
        nxt = all_strokes[i + 1][1][0]
        pieces.append(("move", None, np.array([pts[-1], nxt]), t, t + CONNECT_MS,
                       np.array([0.0, 1.0]), np.ones(2), None))
        t += CONNECT_MS
PEN_END = t

# ---- one continuous pen path, and its offset-distance keyframes ----------------------
pen_pts = [pieces[0][2][0]]
for _, _, pts, _, _, _, _, _ in pieces:
    pen_pts.extend(pts[1:])
pen_pts = np.array(pen_pts)
cum = np.concatenate([[0.0], np.cumsum(np.linalg.norm(np.diff(pen_pts, axis=0), axis=1))])
pen_total = cum[-1]
pen_dur = PEN_END - ALISE_START

# A keyframe per piece is no longer enough: speed now varies WITHIN a stroke, and CSS
# interpolates offset-distance linearly between keyframes, so the dot would cut the
# corner off every speed change and drift off the ink front. Emit one wherever the
# weight steps, plus a floor of KF_PER_STROKE evenly spaced, so the dot and the ink stay
# locked together whatever the routing does.
frames, walked = [], 0
for pi, (kind, gi, pts, t0, t1, tfrac, w, si) in enumerate(pieces):
    n = len(pts)
    marks = {0, n - 1}
    if kind == "ink":
        steps = np.nonzero(np.diff(w))[0]
        marks.update(steps.tolist())
        marks.update((steps + 1).tolist())
        marks.update(np.linspace(0, n - 1, KF_PER_STROKE, dtype=int).tolist())
    for i in sorted(marks):
        if i == n - 1 and pi < len(pieces) - 1:
            continue                      # the next piece emits this instant
        frames.append(((t0 + tfrac[i] * (t1 - t0) - ALISE_START) / pen_dur * 100,
                       cum[walked + i] / pen_total * 100))
    walked += n - 1
frames.append((100.0, 100.0))
frames = sorted(dict((round(p, 3), d) for p, d in frames).items())

kf = ["      0% { opacity: 1; offset-distance: 0%; }"]
for pct, dist in frames[1:-1]:
    kf.append(f"      {pct:.3f}% {{ offset-distance: {dist:.3f}%; }}")
kf.append("      99.9% { offset-distance: 100%; opacity: 1; }")
kf.append("      100% { offset-distance: 100%; opacity: 0; }")
pen_keyframes = "    @keyframes pen-move {\n" + "\n".join(kf) + "\n    }"

# ---- mask segments, per letter -------------------------------------------------------
seg_by_letter = {i: [] for i in range(5)}
maxw = {i: 0 for i in range(5)}

# ONE width per letter, and that is the whole point of it.
#
# Each segment is a round-capped stroke, so the revealed region is the union of a chain of
# discs. Give each segment its own width — which the coverage figures invite, since the
# requirement varies along a letter — and that chain becomes a lumpy sausage: bulge,
# pinch, bulge. Wherever a segment's disc is narrower than the glyph is thick, the glyph's
# own edge is not reached and a notch shows, which fills in a moment later when a wider
# neighbour arrives. The `s` ran 258-422 across its length and looked like a caterpillar
# rather than a pen — the ink is visible before the stroke that makes it exists, which is
# exactly what it must not do. Reported 2026-08-12.
#
# A single radius per letter has none of that: the front is one clean round pen tip and
# the reveal boundary is the glyph's own edge everywhere behind it. It costs some ink
# appearing marginally further ahead of the dot on the thin parts, which is the trade, and
# the ink-vs-pen check is what says whether that trade has gone too far.
#
# Per LETTER rather than per word: one width for all five would size every letter to the
# fattest part of the fattest one, and that margin is what runs ahead of the pen.
width_by_letter = {}
for gi in range(5):
    idxs = [n for n, (g2, _) in enumerate(all_strokes) if g2 == gi]
    width_by_letter[gi] = max(float(cov_by_stroke[n].max()) for n in idxs) * 2 * MASK_SAFETY

# THE REVEAL: one thin ownership slice per step of the journey, switched on whole as the
# pen reaches it. Nothing is swept and nothing is masked - build_centerlines.py's
# ownership_bands() carries the reasoning for why the swept disc had to go.
#
# A slice's clip is exactly the ink the pen lays during that step, so the boundary between
# two consecutive slices is the cut across the stroke that a pen leaves, and the letter's
# own outline is the only other edge on screen. There is no cap to flatten or round, no
# disc to scallop or cusp, and no blob to dump at a letter's start.
#
# Ink leads the pen by at most one slice: a slice switches on when the pen arrives at its
# START, so its far end is inked while the pen crosses it. At 24 slices that is ~4% of a
# letter - inside the pen dot's own radius - and it is what makes the dot read as laying
# the ink rather than chasing it.
ink_slices, ink_fills, ink_keyframes = [], [], []
slice_n = {}
for pi, (kind, gi, pts, t0, t1, tfrac, w_arr, si) in enumerate(pieces):
    if kind != "ink":
        continue
    maxw[gi] = width_by_letter[gi]
    seg = np.linalg.norm(np.diff(pts, axis=0), axis=1)
    afrac = np.concatenate([[0.0], np.cumsum(seg)])
    # A degenerate stroke (every point identical) has total length 0, and numpy
    # divides by it without raising — it warns to stderr and hands back NaN,
    # which then bakes garbage slice-reveal timing into the shipped animation.
    # Refuse it out loud instead.
    total = afrac[-1]
    assert total > 0, (
        f"zero-length stroke in {LETTERS[gi]!r} (piece {pi}) — its centreline points are all "
        "the same; re-run build_centerlines.py"
    )
    afrac /= total
    for band in geom[gi].get("bands") or []:
        # The settle pass is a clip with no stretch of journey behind it - it fires when
        # the letter is finished - so it is kept out of the arithmetic below.
        if band.get("fill"):
            ink_fills.append((gi, band["d"], t1))
            continue
        # When does the pen reach the start of this slice? afrac is distance along the
        # path, tfrac is the pacing curve, and the two are indexed together - so this
        # inherits the pen's own slowing and hurrying rather than assuming constant speed.
        i0 = min(int(np.searchsorted(afrac, band["t0"], "left")), len(pts) - 1)
        at = t0 + tfrac[i0] * (t1 - t0)
        k = slice_n.get(gi, 0)
        slice_n[gi] = k + 1
        ink_slices.append((gi, k, band["d"], at, band["t0"]))

# ---- emit ----------------------------------------------------------------------------
# The glyph is defined ONCE per letter and <use>d by each band, so splitting a letter into
# bands costs a clip path and a mask each, not another copy of the outline.
new_groups = []
for gi in range(5):
    L, defs, uses = LETTERS[gi], [], []
    defs.append(f'<path id="glyph-{L}" d="{letter_paths[gi]}"/>')

    # THE REVEAL IS THE SLICES, GATED ONE AT A TIME - the model Reuben approved, restored
    # (2026-08-13, end of day) after a detour through a swept-mask front that is worth
    # recording so nobody walks it again.
    #
    # The sweep (a stroke grown along the centreline, masking the glyph) was added to make
    # the moving front a smooth cut instead of a rasterised slice boundary. It cannot work
    # alone - barely wider than the letter's stroke it still reaches sideways across gaps,
    # so limbs appear before the pen writes them - and with ownership clips holding it
    # honest, every piece boundary it crossed showed as an axe/bowtie wedge at the letter's
    # head, WORSE than the defect it replaced. Butt caps cut flat wedges at pen-down, round
    # caps reveal a half-disc ahead of the pen, and a run-up bends back through a curved
    # opening and reveals a chunk at t=0. Every variant was screenshotted at 6x and each
    # traded one artefact for a bigger one.
    #
    # What actually fixed the reported defects was never the sweep - it was the GEOMETRY:
    #   - the `a`'s entry flick drawn on the way back up (ROUTE), not first, so no stub
    #     strands at the top; the `s` entered bottom-left (HINTS) so it flows up, over,
    #     and down into the curl; the `i` exited at its dot so the tittle lands last.
    #   - the retrace rule in ownership_bands(), which gives a doubled-back stroke its
    #     full width on the first pass instead of splitting it down the middle (the
    #     half-width notch at the top of the `s` and the `a`'s right side).
    #   - the tittle as ONE atomic band (DABS), so the dot lands whole - a dab, the way a
    #     hand dots an i when signing - not as swept fragments with a bite out of it.
    #   - HEAD_FRAC's finer slices at each pen-down, so a wide start reveals in small
    #     quick steps rather than one blob.
    # With those in the geometry, the plain slice reveal is clean: each slice's boundary
    # is a near-perpendicular cut across the stroke (seventh addendum), and the only edges
    # on screen are the letter's outline and that cut.
    for g2, k, clip_d, at, _t0f in ink_slices:
        if g2 != gi or not clip_d:
            continue
        defs.append(f'<clipPath id="sl-{L}-{k}"><path d="{clip_d}"/></clipPath>')
        uses.append(f'<g clip-path="url(#sl-{L}-{k})">'
                    f'<use href="#glyph-{L}" class="wm-letter wm-slice" '
                    f'style="--sliceAt:{at:.0f}ms"/></g>')
    # Last, so it sits on top: anything the slices did not tile, inked once the letter is
    # written. Normally empty - the slices tile the ownership map - but a hole in a
    # finished letter is the one failure that must not be possible.
    for g2, clip_d, at in ink_fills:
        if g2 != gi or not clip_d:
            continue
        defs.append(f'<clipPath id="settle-{L}"><path d="{clip_d}"/></clipPath>')
        uses.append(f'<g clip-path="url(#settle-{L})">'
                    f'<use href="#glyph-{L}" class="wm-letter wm-settle" '
                    f'style="--settleAt:{at:.0f}ms"/></g>')
    # The glyph and the clip paths MUST sit inside <defs>. A bare <path> that is merely
    # referenced still renders where it stands, and with no class on it that is the
    # glyph's fill with no stroke - 29% of each letter, painted on the page from load.
    body = ("            <defs>\n              " + "\n              ".join(defs)
            + "\n            </defs>\n            " + "\n            ".join(uses))
    new_groups.append(f'        <g>\n{body}\n        </g>')
pen_d = "M" + " L".join(f"{p[0]:.1f} {p[1]:.1f}" for p in pen_pts)
new_groups.append(
    f'        <circle class="wm-pen-dot" r="{DOT_R}" aria-hidden="true"\n'
    f"          style=\"offset-path: path('{pen_d}');--penDelay:{ALISE_START}ms;--penDur:{pen_dur:.0f}ms\"/>")

BEG, END = "<!-- wordmark:begin (generated by tools/wordmark/gen_pen.py) -->", "<!-- wordmark:end -->"
block = BEG + "\n" + "\n".join(new_groups) + "\n        " + END
if BEG in html:
    html = re.sub(re.escape(BEG) + r".*?" + re.escape(END), lambda m: block, html, flags=re.S)
else:
    start = html.index('        <g style="--revealDelay:')
    end = html.rindex("</g>") + len("</g>")
    html = html[:start] + "        " + block + html[end:]

html = re.sub(r"    @keyframes dot-r-\w+ \{.*?\}\n", "", html, flags=re.S)
html = re.sub(r"    @keyframes ink-reveal \{.*?\n    \}\n?", "", html, flags=re.S)

# All the generated keyframes live inside ONE delimited region: the pen's offset-distance
# curve plus a dashoffset curve per letter. It has to be delimited rather than matched
# block-by-block, because the count is no longer fixed - a plain "replace @keyframes
# pen-move" would leave last run's five ink-* blocks behind and they would accumulate.
KBEG = "    /* wordmark-keyframes:begin (generated by tools/wordmark/gen_pen.py) */"
KEND = "    /* wordmark-keyframes:end */"
SETTLE_CSS = (
    "    /* THE REVEAL. Each slice of a letter is a clipped copy of the glyph that is off\n"
    "       until the pen reaches it and on from then on - that switch is the whole\n"
    "       animation. `1ms` rather than `0s` because a zero-duration animation is not\n"
    "       required to fire its fill, and `both` is what holds the 0% state through the\n"
    "       delay so nothing is on the page before its turn.\n"
    "\n"
    "       The hiding MUST sit behind the same html.wm-motion gate as the rest of the reveal\n"
    "       (see the head script, and the .wm-note/.wm-caret/.wm-pen-dot rules above) rather than\n"
    "       a bare @media (prefers-reduced-motion: no-preference). A media query alone races\n"
    "       first paint in real Safari: matching a system accessibility setting isn't guaranteed\n"
    "       resolved by the first style pass, so the base (visible) rule can paint for a frame\n"
    "       before the query's hiding rule lands - a flash of the finished word right before it\n"
    "       blanks and replays. `html.wm-motion` is set by a synchronous head script before any\n"
    "       of this markup is parsed, so there is nothing left to race. Under reduced motion, or\n"
    "       with JS off, the class is never added, so a bare `opacity: 0` here would leave the\n"
    "       wordmark blank instead of showing the finished word - outside the gate they still\n"
    "       default to visible, same as before. */\n"
    "    @keyframes wm-settle { to { opacity: 1; } }\n"
    "    html.wm-motion .wm-slice  { opacity: 0; animation: wm-settle 1ms linear var(--sliceAt) both; }\n"
    "    html.wm-motion .wm-settle { opacity: 0; animation: wm-settle 1ms linear var(--settleAt) both; }")
kblock = "\n".join([KBEG, pen_keyframes] + ink_keyframes + [SETTLE_CSS, KEND])
if KBEG in html:
    html = re.sub(re.escape(KBEG) + r".*?" + re.escape(KEND), lambda m: kblock, html, flags=re.S)
elif "@keyframes pen-move" in html:
    html = re.sub(r"    @keyframes pen-move \{.*?\n    \}", lambda m: kblock, html, flags=re.S)
else:
    # The last of the three recognised shapes. If this one doesn't match either,
    # there is nowhere to put the keyframes and the page would be written with none.
    html = must_replace(
        html,
        "    @keyframes dot-trace {\n"
        "      0%, 0.1% { offset-distance: 0%;   opacity: 0; }\n"
        "      0.2%     { offset-distance: 0%;   opacity: 1; }\n"
        "      99.9%    { offset-distance: 100%; opacity: 1; }\n"
        "      100%     { offset-distance: 100%; opacity: 0; }\n"
        "    }",
        kblock,
        "the keyframes block (no marker, no pen-move, no dot-trace)")
# NOT wrapped in must_change: a no-op here is the normal case on every run after the
# first, since the pre-generation form is only present once. The check that matters
# is that the finished rule is in the file either way, which is asserted below.
html = html.replace(
    '      .wm-pen-dot {\n'
    '        animation: dot-trace var(--revealDur) ease-in-out var(--revealDelay) both,\n'
    '                   var(--dotR) var(--revealDur) linear var(--revealDelay) both;\n      }',
    '      .wm-pen-dot { animation: pen-move var(--penDur) linear var(--penDelay) forwards; }')
if "animation: pen-move" not in html:
    sys.exit("gen_pen: .wm-pen-dot is not wired to pen-move — the page's dot rule is in "
             "neither the pre-generation nor the generated form")
# The nudge is `top`, NOT `vertical-align`. .wordmark is inline-flex, so alise is a flex
# item, and vertical-align does not apply to flex items at all - the value written here
# until 2026-08-12 was inert, which is why alise still sat visibly low after the pass that
# "fixed" it. margin-bottom is no good either: a flex item's baseline is synthesised from
# its border box, so margin does not shift it. Verified all four mechanisms in a real
# browser (DESIGN.md, tenth pass). Rewrites the whole declaration block so it is
# idempotent whichever form is currently in the file.
html = must_sub(
    r"\.wm-alise-svg \{[^}]*\}",
    ".wm-alise-svg { display: inline-block; margin-left: 0.06em; overflow: visible;\n"
    f"      position: relative; top: -{NUDGE:.5f}em; }}",
    html, "the .wm-alise-svg rule", count=1)
html = must_sub(
    r'style="height:[\d.]+em;width:[\d.]+em"',
    f'style="height:{0.6463*ALISE_SCALE:.4f}em;width:{1.9194*ALISE_SCALE:.4f}em"',
    html, "the alise svg's height/width style")

open(HTML, "w", encoding="utf-8").write(html)
print("strokes:", len(all_strokes), " pen ends:", round(PEN_END), "ms  (was 4900)")
print(f"alise: scale {ALISE_SCALE}, raised {NUDGE:.5f}em via `top`")
# The reveal no longer strokes anything, so this width is not used to draw with. It is
# still the honest check that the CENTRELINE reaches the whole letter: it is twice the
# furthest any painted pixel sits from the pen's path, so a figure far above the pen dot
# still means a limb the pen never really visits, whatever the reveal does with it.
widths = {LETTERS[i]: round(maxw[i]) for i in range(5)}
print("centreline reach per letter:", widths, f" (pen dot diameter {DOT_R*2})")
worst = max(maxw.values()) / (DOT_R * 2)
print(f"furthest ink from the pen path is {worst:.1f}x the pen dot"
      f"{'' if worst < 2.0 else '   <-- TOO FAR: a letter has a limb the pen never reaches'}")
per = {}
for gi, _, _, _, _ in ink_slices:
    per[LETTERS[gi]] = per.get(LETTERS[gi], 0) + 1
print("reveal slices per letter:", per)
